# Generated by Django 3.2.5 on 2021-08-05 14:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=200, verbose_name='Наименование района')),
                ('area_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Стоимость доставки')),
                ('area_description', models.TextField(verbose_name='Описание района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=200, verbose_name='Наименование статуса')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='Наименование продукта')),
                ('product_unit', models.CharField(max_length=200, verbose_name='Ед. измерения')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('product_description', models.TextField(verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 50, 8, 845686, tzinfo=utc), verbose_name='Дата заказа')),
                ('order_timezone', models.CharField(max_length=6, verbose_name='Timezone')),
                ('order_name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('order_phone', models.CharField(max_length=200, verbose_name='Телефон заказчика')),
                ('order_count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('order_address', models.CharField(max_length=500, verbose_name='Адрес доставки')),
                ('order_date_delivery', models.DateField(verbose_name='Дата доставки')),
                ('order_time_delivery', models.TimeField(verbose_name='Время доставки')),
                ('order_description', models.TextField(blank=True, null=True, verbose_name='Описание заказа')),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('area_id', models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='app_order.areas')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='app_order.products')),
                ('status_id', models.ForeignKey(db_column='status_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_order.orderstatus')),
                ('user_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
