# Generated by Django 3.2.5 on 2021-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_auto_20210825_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
