# Generated by Django 3.2.5 on 2021-08-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_products_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Наименование статуса'),
        ),
    ]
