# Generated by Django 3.2.5 on 2021-08-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_alter_orderstatus_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
