# Generated by Django 3.2.5 on 2021-08-28 14:10

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0007_alter_orders_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 14, 9, 18, 6995, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
