# Generated by Django 3.2.5 on 2021-08-29 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0008_auto_20210828_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 15, 25, 25, 660471, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
