# Generated by Django 3.2.5 on 2021-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0010_auto_20210830_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
