# Generated by Django 3.2.5 on 2021-08-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0012_auto_20210830_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(db_column='slug', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_order.orderstatus'),
        ),
    ]
