# Generated by Django 3.2.5 on 2021-08-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0013_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(db_column='status_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_order.orderstatus'),
        ),
    ]
