# Generated by Django 3.2.5 on 2021-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0014_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование единицы измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['unit_id', 'unit_name'],
            },
        ),
    ]
