# Generated by Django 3.2.5 on 2021-09-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0015_productunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_unit',
            field=models.ForeignKey(db_column='unit_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_order.productunit'),
        ),
    ]
