# Generated by Django 3.2.5 on 2021-09-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0016_alter_products_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
