# Generated by Django 3.2.5 on 2021-09-09 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0017_alter_products_product_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 19, 42, 3, 19829, tzinfo=utc), verbose_name='Дата статуса'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.'),
        ),
    ]
