# Generated by Django 3.2.5 on 2021-09-11 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0019_auto_20210909_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 9, 16, 20, 163051, tzinfo=utc), verbose_name='Дата статуса'),
        ),
    ]
