# Generated by Django 3.2.5 on 2021-09-11 09:28

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0020_auto_20210911_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 9, 28, 56, 277420, tzinfo=utc), verbose_name='Дата статуса'),
        ),
    ]
