# Generated by Django 3.2.5 on 2021-09-29 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0022_auto_20210911_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 5, 53, 2, 709387, tzinfo=utc), verbose_name='Дата статуса'),
        ),
    ]
