# Generated by Django 3.2.5 on 2021-10-02 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0023_auto_20210929_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 14, 10, 57, 576886, tzinfo=utc), verbose_name='Дата статуса'),
        ),
    ]
