# Generated by Django 3.2.5 on 2021-10-02 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0024_auto_20211002_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 14, 12, 9, 870852, tzinfo=utc), verbose_name='Дата статуса'),
        ),
    ]
